### ISSUE TITLE
What's the weather like in Phuipford, Kishire?

### ISSUE THREAD

**Issue by boi87** [fac-15/weatherTunes#18]
I couldn't find out the weather is over there, why? Because the city doesn't exist, nor does the county.
But how does your app deal with non-existing places? :vertical_traffic_light: 

However your input field blocked me when I tried to input symbols! Well done! :astonished:

**Comment by martingaston** [comment]
One way to do this is to look at building out your code in `logic.js` - your XHR has an if conditional for what happens if we get a 200, but you could have an else there to catch 404 or any other nebulous result.

**Comment by mr-bagglesworth** [comment]
This is addressed in commit 5a62cb5.
One general error message has been added to catch things that don't exist in openweathermap.
It would be a stretch goal to handle duplicate cities and whatnot, we were thinking of either:
- matching against an array of cities
- using a sort of autocomplete function to search the API as you type
